In [1]:
import pandas as pd
dict_data = {"a":1,"b":2,"c":3}
sr = pd.Series(dict_data)
print(sr)

a    1
b    2
c    3
dtype: int64

In [2]:
print(type(sr))

<class 'pandas.core.series.Series'>

In [6]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9],'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data)
print(df)
print(type(df))

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15
<class 'pandas.core.frame.DataFrame'>

In [25]:
name_series = pd.Series(['김수안', '김수정', '박동윤', '강이안', '강지안'])
age_series = pd.Series([19, 23, 22, 19, 16])
sex_series = pd.Series(['여', '남', '남', '여', '남'])
grade_series = pd.Series([1,2,3,2,1])

df = pd.DataFrame({'이름':name_series, '나이':age_series, '성별':sex_series, '등급':grade_series})
#데이터 프레임 형태로? df함수 안에 넣어줌 
df

    이름  나이 성별  등급
0  김수안  19  여   1
1  김수정  23  남   2
2  박동윤  22  남   3
3  강이안  19  여   2
4  강지안  16  남   1

In [12]:
ltk = ['1월','2월','3월','4월','5월','6월']
lt = [4.1,5.5,9.0,15.0,19.0,21.3]
sr = pd.Series(lt,index=ltk)
sr

1월     4.1
2월     5.5
3월     9.0
4월    15.0
5월    19.0
6월    21.3
dtype: float64

In [13]:
print(sr['4월':]) #4월부터 쭉

4월    15.0
5월    19.0
6월    21.3
dtype: float64

In [14]:
print(sr[sr.index>'4월']) #4월보다 큰

5월    19.0
6월    21.3
dtype: float64

In [19]:
print(sr[sr>5.5]) #값이 5.5보다 큰행

3월     9.0
4월    15.0
5월    19.0
6월    21.3
dtype: float64

In [34]:
area = ['서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기',
'강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주']

pm25_avg = [20,13,15,20,19,16,14,18,20,14,19,23,23,14,15,13,14]
pm25_max = [22,18,18,30,23,20,16,19,27,18,26,29,30,27,23,17,16]
pm25_min = [16,10,11,12,15,12,11,17,13,9,14,19,14,10,8,9,11]

df = pd.DataFrame() # 빈 데이터프레임 생성
df['지역'] = area # ‘지역’ 열 생성
df['평균'] = pm25_avg # ‘평균’ 열 생성
df['최대'] = pm25_max # ‘최대’ 열 생성
df['최소'] = pm25_min # ‘최소’ 열 생성

df

print(df.loc[1,'지역'])
print(df.loc[1:3,'지역':'최대'])
print(df.loc[[1,3],['지역','최대']])
print("----------")
print(df.iloc[1,0])
print(df.iloc[1:4, 0:3])
print(df.iloc[[1,3], [0,2]])
print("----------")
print(df[df['지역']=='부산']) #부산과 관련된 행 전체 뽑아옴
print(df[df['최대']>=25]) #최대 값이 20 이상인 것
print(df[(df['최소']<=10)&(df['최대']>=25)]) #최소값이 10 이하이고 최대값이 25 이상인 것

부산
   지역  평균  최대
1  부산  13  18
2  대구  15  18
3  인천  20  30
   지역  최대
1  부산  18
3  인천  30
----------
부산
   지역  평균  최대
1  부산  13  18
2  대구  15  18
3  인천  20  30
   지역  최대
1  부산  18
3  인천  30
----------
   지역  평균  최대  최소
1  부산  13  18  10
    지역  평균  최대  최소
3   인천  20  30  12
8   경기  20  27  13
10  충북  19  26  14
11  충남  23  29  19
12  전북  23  30  14
13  전남  14  27  10
    지역  평균  최대  최소
13  전남  14  27  10

In [2]:
import pandas as pd

In [35]:
df.info()
#값이 정해지지 않은 값은 null로 나온다?

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 아우디폭스바겐코리아(주) to 기아 주식회사
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   모델명     200 non-null    object
 1   표시연비    200 non-null    float64
 2   배기량     200 non-null    int64
 3   co2배출량  200 non-null    int64
 4   등급      200 non-null    int64
 5   연간유류비   200 non-null    int64
dtypes: float64(1), int64(4), object(1)
memory usage: 10.9+ KB

In [36]:
df = pd.read_csv("C:/Users/user/Downloads/car (1).csv") 
df

,업체명,모델명,표시연비,배기량,co2배출량,등급,연간유류비
0,아우디폭스바겐코리아(주),A4 35 TDI,16.9,1968,110,1,1209959
1,한불모터스(주),Peugeot 508 1.5 BlueHDi_(18inch tire),17.2,1499,108,1,1188855
2,한불모터스(주),Peugeot 508SW 1.5 BlueHDi_(18inch tire),17.2,1499,108,1,1188855
3,한불모터스(주),Peugeot 308 1.5 BlueHDi,17.1,1499,109,1,1195807
4,쌍용자동차㈜,코란도 1.6 디젤 6MT 2WD SCR Step2,16.0,1597,117,1,1278019
...,...,...,...,...,...,...,...
195,FCA코리아㈜,짚 레니게이드 1.6,15.6,1598,120,2,1310788
196,현대자동차㈜,"코나 1.6디젤 4WD (17"" 타이어)",15.3,1598,123,2,1336490
197,현대자동차㈜,"코나 1.6디젤 4WD (18"" 타이어)",14.6,1598,129,2,1400568
198,현대자동차㈜,"코나 1.6디젤 4WD (16""타이어)",15.7,1598,119,2,1302439
199,기아 주식회사,"K7 2.2디젤 (PE/18""타이어)",14.5,2199,131,2,1410228

In [37]:
#2. 값들의 평균값, 표준편차, 최소값, 최대값, 사분위수 나타내기
df.describe()

             표시연비          배기량     co2배출량          등급         연간유류비
count  200.000000   200.000000  200.00000  200.000000  2.000000e+02
mean    15.810500  1839.930000  114.39000    1.630000  1.373007e+06
std      1.777537   283.807892   17.74549    0.484016  1.293492e+05
min     13.800000  1332.000000   68.00000    1.000000  1.047462e+06
25%     14.300000  1598.000000  104.75000    1.000000  1.292161e+06
50%     15.300000  1950.000000  118.00000    2.000000  1.372369e+06
75%     16.900000  1999.000000  130.00000    2.000000  1.448343e+06
max     22.400000  2487.000000  138.00000    2.000000  1.700228e+06

In [38]:
#3. 이산화탄소 배출량이 115 이상이고, 등급이 1등급인 행 출력하기
df[(df['co2배출량']>=115)&(df['등급']==1)]

,업체명,모델명,표시연비,배기량,co2배출량,등급,연간유류비
4,쌍용자동차㈜,코란도 1.6 디젤 6MT 2WD SCR Step2,16.0,1597,117,1,1278019
8,기아 주식회사,"셀토스 1.6디젤 2WD 18"" 타이어 (21)",16.1,1598,116,1,1270081
14,메르세데스-벤츠코리아(주),Mercedes-Benz A200 d,16.1,1950,116,1,1270081
42,기아 주식회사,"셀토스 1.6디젤 4WD (16"" 타이어)",16.1,1598,116,1,1270081
56,현대자동차㈜,"투싼 개조차 1.6디젤 2WD (17""타이어)",16.3,1598,115,1,1254497
59,BMW코리아㈜,MINI Cooper SD,16.1,1995,116,1,1270081

In [20]:
#4. 이산화탄소 배출량, 배기량으로 내림차순 정렬
df.sort_values(by=['co2배출량'], ascending=False)

,업체명,모델명,표시연비,배기량,co2배출량,등급,연간유류비
140,아우디폭스바겐코리아(주),A4 40 TDI quattro,13.8,1968,138,2,1481761
189,현대자동차㈜,"투싼 개조차 1.6디젤 AWD (20MY_19""타이어)",13.8,1598,137,2,1481761
187,현대자동차㈜,"투싼 개조차 2.0디젤 2WD 8AT (20MY_19""타이어)",13.8,1995,137,2,1481761
98,기아 주식회사,스포티지 1.6디젤 4WD (PE/18“ 타이어)(21),13.9,1598,137,2,1471101
115,현대자동차㈜,투싼 2.0디젤 2WD 8AT 19인치 (빌트인캠),13.9,1998,137,2,1471101
...,...,...,...,...,...,...,...
71,현대자동차㈜,아이오닉 1.6GDI 하이브리드 6DCT_17''타이어,20.2,1580,78,1,1161542
26,한국토요타자동차㈜,토요타 Prius AWD,20.9,1798,74,1,1122639
22,현대자동차㈜,아반떼 1.6GDI 하이브리드 (16“타이어),21.1,1580,74,1,1111998
70,현대자동차㈜,아이오닉 1.6GDI 하이브리드 6DCT_15''타이어,22.4,1580,69,1,1047462
45,한국토요타자동차㈜,토요타 Prius 2WD,22.4,1798,68,1,1047462

In [33]:
#4
df.sort_values(by=['배기량'], ascending=False)

                               모델명  표시연비   배기량  co2배출량  등급    연간유류비
업체명
한국토요타자동차㈜      토요타 Camry Hybrid LE  17.5  2487      92   1  1340751
한국토요타자동차㈜        토요타 Avalon Hybrid  16.6  2487      96   1  1413443
한국토요타자동차㈜               렉서스 ES300h  17.0  2487      93   1  1380185
한국토요타자동차㈜      토요타 RAV4 Hybrid 2WD  15.7  2487     101   2  1494468
한국토요타자동차㈜         토요타 Camry Hybrid  16.7  2487      95   1  1404979
...                            ...   ...   ...     ...  ..      ...
한국토요타자동차㈜              토요타 Prius C  18.6  1497      84   1  1261460
BMW코리아㈜              MINI Cooper D  16.9  1496     109   1  1209959
BMW코리아㈜    MINI Cooper D Five Door  16.5  1496     113   1  1239291
르노삼성자동차㈜         CAPTUR 1.5 DIESEL  17.7  1461     104   1  1155271
르노삼성자동차㈜   XM3 1.3 (17" tire) LRRC  13.8  1332     119   2  1700228

[200 rows x 6 columns]

In [48]:
#4 (합쳐서 본 버전)
df.sort_values(by=['co2배출량', '배기량'], ascending=False)

,업체명,모델명,표시연비,배기량,co2배출량,등급,연간유류비
140,아우디폭스바겐코리아(주),A4 40 TDI quattro,13.8,1968,138,2,1481761
149,기아 주식회사,쏘렌토 2.2디젤 4WD 5인 18인치타이어,13.9,2151,137,2,1471101
114,현대자동차㈜,투싼 2.0디젤 2WD 8AT 19인치,13.9,1998,137,2,1471101
115,현대자동차㈜,투싼 2.0디젤 2WD 8AT 19인치 (빌트인캠),13.9,1998,137,2,1471101
187,현대자동차㈜,"투싼 개조차 2.0디젤 2WD 8AT (20MY_19""타이어)",13.8,1995,137,2,1481761
...,...,...,...,...,...,...,...
71,현대자동차㈜,아이오닉 1.6GDI 하이브리드 6DCT_17''타이어,20.2,1580,78,1,1161542
26,한국토요타자동차㈜,토요타 Prius AWD,20.9,1798,74,1,1122639
22,현대자동차㈜,아반떼 1.6GDI 하이브리드 (16“타이어),21.1,1580,74,1,1111998
70,현대자동차㈜,아이오닉 1.6GDI 하이브리드 6DCT_15''타이어,22.4,1580,69,1,1047462
45,한국토요타자동차㈜,토요타 Prius 2WD,22.4,1798,68,1,1047462

In [57]:
#업체명 나타내기
df['업체명'].unique()

array(['아우디폭스바겐코리아(주)', '한불모터스(주)', '쌍용자동차㈜', '혼다코리아(주)', '기아 주식회사',
       '한국토요타자동차㈜', '메르세데스-벤츠코리아(주)', '현대자동차', '현대자동차㈜', '르노삼성자동차㈜',
       '한국지엠주식회사', 'BMW코리아㈜', '포드세일즈서비스코리아(유)', 'FCA코리아㈜',
       '(주)재규어랜드로버코리아'], dtype=object)

In [62]:
df['구분'] = ['국산'if item in ['쌍용자동차㈜', '기아 주식회사', '현대자동차㈜'] else '수입' for item in list(df['업체명'])]
df

,업체명,모델명,표시연비,배기량,co2배출량,등급,연간유류비,구분
0,아우디폭스바겐코리아(주),A4 35 TDI,16.9,1968,110,1,1209959,수입
1,한불모터스(주),Peugeot 508 1.5 BlueHDi_(18inch tire),17.2,1499,108,1,1188855,수입
2,한불모터스(주),Peugeot 508SW 1.5 BlueHDi_(18inch tire),17.2,1499,108,1,1188855,수입
3,한불모터스(주),Peugeot 308 1.5 BlueHDi,17.1,1499,109,1,1195807,수입
4,쌍용자동차㈜,코란도 1.6 디젤 6MT 2WD SCR Step2,16.0,1597,117,1,1278019,국산
...,...,...,...,...,...,...,...,...
195,FCA코리아㈜,짚 레니게이드 1.6,15.6,1598,120,2,1310788,수입
196,현대자동차㈜,"코나 1.6디젤 4WD (17"" 타이어)",15.3,1598,123,2,1336490,국산
197,현대자동차㈜,"코나 1.6디젤 4WD (18"" 타이어)",14.6,1598,129,2,1400568,국산
198,현대자동차㈜,"코나 1.6디젤 4WD (16""타이어)",15.7,1598,119,2,1302439,국산
199,기아 주식회사,"K7 2.2디젤 (PE/18""타이어)",14.5,2199,131,2,1410228,국산

In [63]:
df.corr()

ValueError: could not convert string to float: '아우디폭스바겐코리아(주)'