In [31]:
import pandas as pd
df = pd.read_csv("weather1.csv", encoding='cp949')
df

               날짜   지점  평균기온(℃)  최저기온(℃)  최고기온(℃)
0      1980-04-01  108      6.5      3.2     11.7
1      1980-04-02  108      6.5      1.4     12.9
2      1980-04-03  108     11.1      4.1     18.4
3      1980-04-04  108     15.5      8.6     21.0
4      1980-04-05  108     15.4     12.5     18.2
...           ...  ...      ...      ...      ...
14278  2019-05-05  108     19.2     13.6     26.5
14279  2019-05-06  108     14.5      9.8     19.8
14280  2019-05-07  108     15.0      8.4     21.9
14281  2019-05-08  108     15.6     10.1     21.3
14282  2019-05-09  108     16.6     11.7     22.9

[14283 rows x 5 columns]

In [46]:
#1
df.describe()

,날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃),년도
count,14283,14283.0,14283.000000,14283.000000,14282.000000,14283.000000
mean,1999-10-19 23:59:59.999999872,108.0,12.625163,8.689904,17.202269,1999.300987
min,1980-04-01 00:00:00,108.0,-16.400000,-19.200000,-13.600000,1980.000000
25%,1990-01-09 12:00:00,108.0,3.700000,0.000000,8.000000,1990.000000
50%,1999-10-20 00:00:00,108.0,14.100000,9.400000,19.050000,1999.000000
75%,2009-07-29 12:00:00,108.0,22.000000,18.100000,26.500000,2009.000000
max,2019-05-09 00:00:00,108.0,33.700000,30.300000,39.600000,2019.000000
std,NaN,0.0,10.394245,10.462389,10.628355,11.294473

In [39]:
#2. 날짜에 대해 to_datetime으로 바꾸고 ‘년도’ 열 추가하기
df['날짜'] = pd.to_datetime(df['날짜']) #날짜 열 datetime 형식으로 바꿈
df['년도'] = df['날짜'].dt.year
df.head()

          날짜   지점  평균기온(℃)  최저기온(℃)  최고기온(℃)    년도
0 1980-04-01  108      6.5      3.2     11.7  1980
1 1980-04-02  108      6.5      1.4     12.9  1980
2 1980-04-03  108     11.1      4.1     18.4  1980
3 1980-04-04  108     15.5      8.6     21.0  1980
4 1980-04-05  108     15.4     12.5     18.2  1980

In [51]:
#3. 몇 년도에 최대 기온이 나타나는가?
year_max = df.groupby('년도')['최고기온(℃)'].max()
print("최고 기온 발생 년도 :", year_max.idxmax())
print("최고 기온 :", year_max.max())

최고 기온 발생 년도 : 2018
최고 기온 : 39.6

In [49]:
#4. 몇 년도의 최소 기온이 가장 낮았는가?
year_min = df.groupby('년도')['최저기온(℃)'].min()

print("최소 기온 발생 년도 :", year_min.idxmin())  # 최저기온이 가장 낮았던 연도
print("최소 기온 :", year_min.min())

최소 기온 발생 년도 : 1986
최소 기온 : -19.2

In [47]:
#5. 평균 기온이 15 이상인 날 구하기
a = df[df['평균기온(℃)'] > 15]
a

              날짜   지점  평균기온(℃)  최저기온(℃)  최고기온(℃)    년도
3     1980-04-04  108     15.5      8.6     21.0  1980
4     1980-04-05  108     15.4     12.5     18.2  1980
31    1980-05-02  108     15.6      8.7     22.3  1980
32    1980-05-03  108     15.1     11.7     19.2  1980
39    1980-05-10  108     15.4      9.3     20.9  1980
...          ...  ...      ...      ...      ...   ...
14276 2019-05-03  108     17.9     10.1     26.1  2019
14277 2019-05-04  108     19.5     12.0     27.4  2019
14278 2019-05-05  108     19.2     13.6     26.5  2019
14281 2019-05-08  108     15.6     10.1     21.3  2019
14282 2019-05-09  108     16.6     11.7     22.9  2019

[6719 rows x 6 columns]

In [48]:
#6.연도별 평균기온의 평균 구하기
df.groupby('년도')['평균기온(℃)'].mean()

년도
1980    14.563636
1981    11.226575
1982    12.558630
1983    12.454247
1984    11.596995
1985    11.617808
1986    11.306027
1987    11.986027
1988    12.121311
1989    13.011233
1990    12.838904
1991    12.397534
1992    12.501093
1993    12.084658
1994    13.612329
1995    12.266849
1996    12.257923
1997    12.956712
1998    13.835890
1999    13.256986
2000    12.713661
2001    12.859726
2002    12.914247
2003    12.869589
2004    13.351639
2005    12.139452
2006    13.061918
2007    13.282740
2008    12.964208
2009    12.953425
2010    12.140822
2011    12.082192
2012    12.268579
2013    12.563562
2014    13.400274
2015    13.622192
2016    13.592896
2017    13.073151
2018    13.002466
2019     5.698450
Name: 평균기온(℃), dtype: float64